version: '3.8'

services:
  backend:
    build:
      context: ./back
    ports:
      - "8000:8000"
    volumes:
      - ./back/app:/app/app
    depends_on:
      - db

  frontend:
    build:
      context: ./src
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
